/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppState {
  'speakerPushout' : bigint,
  'mergeSwitch' : boolean,
  'sprPressure' : bigint,
  'voiceDepth' : bigint,
  'masterVolume' : bigint,
  'eqBands' : Array<EQBand>,
  'bassAmpSettings' : BassAmpSettings,
  'highMidAmpSettings' : HighMidAmpSettings,
}
export interface BassAmpSettings {
  'soundStageDistance' : bigint,
  'omniField' : boolean,
  'bassCorrection' : bigint,
}
export interface EQBand { 'value' : bigint, 'frequency' : string }
export interface HighMidAmpSettings {
  'thump' : bigint,
  'blocker1' : boolean,
  'blocker2' : boolean,
  'soundStageDistance' : bigint,
  'kick' : bigint,
  'frequency' : bigint,
}
export interface Slot {
  'name' : string,
  'lastModified' : bigint,
  'state' : AppState,
}
export interface _SERVICE {
  'addSystemCleanLog' : ActorMethod<[string], undefined>,
  'deleteSlot' : ActorMethod<[bigint], undefined>,
  'getLastSystemCleanTimestamp' : ActorMethod<[], bigint>,
  'getSlots' : ActorMethod<[], Array<Slot>>,
  'getSystemCleanLogs' : ActorMethod<[], Array<string>>,
  'loadSlot' : ActorMethod<[bigint], AppState>,
  'saveSlot' : ActorMethod<[bigint, string, AppState], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];