/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EQBand = IDL.Record({ 'value' : IDL.Int, 'frequency' : IDL.Text });
export const BassAmpSettings = IDL.Record({
  'soundStageDistance' : IDL.Nat,
  'omniField' : IDL.Bool,
  'bassCorrection' : IDL.Nat,
});
export const HighMidAmpSettings = IDL.Record({
  'thump' : IDL.Nat,
  'blocker1' : IDL.Bool,
  'blocker2' : IDL.Bool,
  'soundStageDistance' : IDL.Nat,
  'kick' : IDL.Nat,
  'frequency' : IDL.Nat,
});
export const AppState = IDL.Record({
  'speakerPushout' : IDL.Nat,
  'mergeSwitch' : IDL.Bool,
  'sprPressure' : IDL.Nat,
  'voiceDepth' : IDL.Nat,
  'masterVolume' : IDL.Nat,
  'eqBands' : IDL.Vec(EQBand),
  'bassAmpSettings' : BassAmpSettings,
  'highMidAmpSettings' : HighMidAmpSettings,
});
export const Slot = IDL.Record({
  'name' : IDL.Text,
  'lastModified' : IDL.Int,
  'state' : AppState,
});

export const idlService = IDL.Service({
  'addSystemCleanLog' : IDL.Func([IDL.Text], [], []),
  'deleteSlot' : IDL.Func([IDL.Nat], [], []),
  'getLastSystemCleanTimestamp' : IDL.Func([], [IDL.Int], ['query']),
  'getSlots' : IDL.Func([], [IDL.Vec(Slot)], ['query']),
  'getSystemCleanLogs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'loadSlot' : IDL.Func([IDL.Nat], [AppState], ['query']),
  'saveSlot' : IDL.Func([IDL.Nat, IDL.Text, AppState], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EQBand = IDL.Record({ 'value' : IDL.Int, 'frequency' : IDL.Text });
  const BassAmpSettings = IDL.Record({
    'soundStageDistance' : IDL.Nat,
    'omniField' : IDL.Bool,
    'bassCorrection' : IDL.Nat,
  });
  const HighMidAmpSettings = IDL.Record({
    'thump' : IDL.Nat,
    'blocker1' : IDL.Bool,
    'blocker2' : IDL.Bool,
    'soundStageDistance' : IDL.Nat,
    'kick' : IDL.Nat,
    'frequency' : IDL.Nat,
  });
  const AppState = IDL.Record({
    'speakerPushout' : IDL.Nat,
    'mergeSwitch' : IDL.Bool,
    'sprPressure' : IDL.Nat,
    'voiceDepth' : IDL.Nat,
    'masterVolume' : IDL.Nat,
    'eqBands' : IDL.Vec(EQBand),
    'bassAmpSettings' : BassAmpSettings,
    'highMidAmpSettings' : HighMidAmpSettings,
  });
  const Slot = IDL.Record({
    'name' : IDL.Text,
    'lastModified' : IDL.Int,
    'state' : AppState,
  });
  
  return IDL.Service({
    'addSystemCleanLog' : IDL.Func([IDL.Text], [], []),
    'deleteSlot' : IDL.Func([IDL.Nat], [], []),
    'getLastSystemCleanTimestamp' : IDL.Func([], [IDL.Int], ['query']),
    'getSlots' : IDL.Func([], [IDL.Vec(Slot)], ['query']),
    'getSystemCleanLogs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'loadSlot' : IDL.Func([IDL.Nat], [AppState], ['query']),
    'saveSlot' : IDL.Func([IDL.Nat, IDL.Text, AppState], [], []),
  });
};

export const init = ({ IDL }) => { return []; };